export default [
    {
        name: '+1',
        short_names: ['+1'],
        text: '',
        emoticons: [],
        keywords: ['thumbsup'],
    },
    {
        name: 'clap',
        short_names: ['clap'],
        text: '',
        emoticons: [],
        keywords: ['clap'],
    },
    {
        name: 'mega',
        short_names: ['mega'],
        text: '',
        emoticons: [],
        keywords: ['mega','cheering megaphone'],
    },
    {
        name: 'zap',
        short_names: ['zap'],
        text: '',
        emoticons: [],
        keywords: ['zap', 'high voltage sign'],
    },
    {
        name: 'rocket',
        short_names: ['rocket'],
        text: '',
        emoticons: [],
        keywords: ['rocket'],
    },
    {
        name: 'fire',
        short_names: ['fire'],
        text: '',
        emoticons: [],
        keywords: ['fire'],
    },
    {
        name: 'hammer_and_wrench',
        short_names: ['hammer_and_wrench'],
        text: '',
        emoticons: [],
        keywords: ['hammer_and_wrench'],
    },
]