export const SITE = {
    SEARCH: "SITE_SEARCH_CLICK",
    NOTIFY: {
        CLEAR: "CLEAR_NOTIFICATIONS",
        PUSH: "PUSH_NOTIFICATION"
    },
    INFINITY: {
        SET_STATE: "INFINITY_PAGE_STATE",
        SET_DATE_OFFSET: "SET_DATE_OFFSET",
        SET_POSTS_OFFSET: "SET_POSTS_OFFSET",
        SET_EXISTS_POSTS: "SET_INFINITY_POSTS_IDS",
        SET_PREV_CATEGORIES: "SET_INFINITY_CATEGORY_IDS",
        SET_CATEGORY_OFFSET: "SET_INFINITY_CATEGORY_OFFSET",
        SET_AVAILABLE_CATEGORIES: "SET_INFINITY_AVAILABLE_CATEGORIES"
    }
}